#!/usr/bin/php
<?php 
require(__DIR__."/roku-make-functions.php");
require(__DIR__."/roku-config.php");
#require(__DIR__."/roku-art.php");
require(__DIR__."/roku-custom.php");
require(__DIR__."/roku-test-functions.php");
require(__DIR__."/roku-sdk.php");

$commands = [];

$longOptions = ["help","showvars"];
$shortOptions = ["?" => "help", "V" => "showvars"];

for ($v = 1; $v < $argc; $v++) {
	if(strpos($argv[$v], '=') !== false) {
		$override = explode('=',$argv[$v]);
		$E[$override[0]] = $override[1];
	} else if(substr($argv[$v], 0, 2) == '--') {
		$option = substr($argv[$v], 2);
		if(in_array($option, $longOptions)) {
			$commands[] = $option;
		} else {
			pl("Unknown option: --".$option);
			help();
		}
	} else if(substr($argv[$v], 0, 1) == '-') {
		$option = substr($argv[$v], 1);
		$shorts = array_keys($shortOptions);
		if(in_array($option, $shorts)) {
			$commands[] = $shortOptions[$option];
		} else {
			pl("Unknown option: -".$option);
			help();
		}
	} else {
		if(!function_exists($argv[$v])) {
			pl("Unknown command: ".$argv[$v]);
			help();
		}
		$commands[] = $argv[$v];
	}
}

if(count($commands) == 0) help();
updateEnv();

if(function_exists("consoleCreate")) $console = consoleCreate();

foreach ($commands as $command) {	
	call_user_func($command);
	$msg = sprintf("*** %s($command) $E[APPFULLNAME] complete ***", basename($argv[0]));
	if(!empty($E['ARTIFACTORY']) and empty($E['ARTIFACTORY_LIST'])) {
		$E['ARTIFACTORY_LIST'] = "";
		if(file_exists("$E[ZIPDIR]/$E[APPFULLNAME].zip")) $E['ARTIFACTORY_LIST'] .= sprintf("\n $E[ARTIFACTORY]/$E[APPFULLNAME].zip ");
		if(file_exists("$E[PKGDIR]/$E[APPFULLNAME].pkg")) $E['ARTIFACTORY_LIST'] .= sprintf("\n $E[ARTIFACTORY]/$E[APPFULLNAME].pkg ");
	}
	if(!empty($E['ARTIFACTORY_LIST'])) {
		$msg .= $E['ARTIFACTORY_LIST'];
		#	exec("git log --after yesterday --pretty=%b | sed '/^$/d'", $output);
		exec("git log -1 --pretty=%B | sed '/^$/d'", $output);
		$msg .= "\nThis Build Includes:\n```".implode("\n",$output)."```";
	}
	finish($msg);
}
?>